# Base configuration
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
markdown: kramdown
highlighter: rouge

collections:
  pages:
    output: true
    permalink: /:path/

# Title
name: Freight Trust Public GitHub
subtitle: Protocol Overview

# When using this template with a project page set the baseurl to '/project-name'
# For user/organization pages set this to an empty string
# When working locally use jekyll serve --baseurl '' so that you can view everything at localhost:4000
# See http://jekyllrb.com/docs/github-pages/ for more info
#baseurl: ''
baseurl: '/'

# Author/Organization info to be displayed in the templates
author:
  name: FreightTrust & Clearing Corporation
  url: http://freighttrust.com

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl:
logoalt:

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Home
  url: ./
  internal: true
- text: Protocol
  url: https://github.com/freight-trust/spec
  internal: false
- text: Corporate GitHub
  url: https://github.com/freight-trust
  internal: false
- text: Community GitHub
  url: https://github.com/freight-chain
  internal: false
- text: Telegram
  url: https://t.ne/freighttrust
  internal: false

# Repo list
# List repos that you would like to appear on the homepage here
repos:

- name: Specifications 
  description: Protocol Specs.
  url: https://github.com/freight-trust/spec

- name: Maidenlane
  description: Protocol
  url: https://gitlab.com/Maidenlane

- name: TradeDocs
  description: Trade Documents
  url: https://github.com/freight-chain/tradedocs

- name: Instruments
  description: Smart Contracts for v1
  url: https://github.com/freight-trust/Instruments

- name: Blockchain
  description: Hyperledger Besu
  url: https://github.com/freight-chain/network

- name: Omnibus v5
  description: Documentation
  url: https://github.com/freight-trust/omnibus

- name: RuleBook
  description: Blockchain RuleBook 
  url: https://github.com/freight-trust/omnibus

- name: Infrastructure
  description: Terraform
  url: https://github.com/freight-trust/Infrastructure

- name: RFC's and Netwokr Improvements
  description: EIP/RFC's
  url: https://github.com/freight-chain/rfc


# Style Variables
brand_color: "#2cb34a"

# Offline caching
offline_cache: false
cache_name: DOCter-v1.1
